### ISSUE TITLE
Folder_watcher fires modified event many times

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Google-Vision#2]
Firing 2-3 times on modifying the saved file resulting in multiple notifications

**Comment by robmarkcole** [comment]
Adding a few delays in an automation resolves this:
```yaml
  action:
.
.
.
    - delay:
        seconds: 1
```
